CREATE TABLE `tbl_applicants` (
  `id` int(11) NOT NULL,
  `companyName` varchar(100) NOT NULL,
  `userName` varchar(100) DEFAULT NULL,
  `userEmail` varchar(100) DEFAULT NULL,
  `userPhone` int(12) DEFAULT NULL,
  `about` varchar(300) DEFAULT NULL,
  `number` int(12) DEFAULT NULL,
  `postTime` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
